### ISSUE TITLE
scalar parse error.

### ISSUE THREAD

**Issue by r4um** [square/grange-server#8]
From the clusters data in this [repo](https://github.com/square/grange-server/blob/master/clusters/dc2-mysql.yaml#L16)

When server starts.

```
WARN  [2016-01-20 13:28:17.552] Could not parse query: %!!(MISSING)s(bool=false)
```
Queries
```
$ erg %dc2-mysql:KEYS
ALL,CLUSTER,DOC,DOWN,EXTRA,PORT,TYPE,UP
$ erg %dc2-mysql:UP
Error:  Could not parse query: %!s(bool=false)
```

**Comment by xaviershay** [comment]
huh weird, I wonder when/how that broke. Thanks for reporting, closing in favour of the linked PR that fixes this issue.
